# Generated by Django 3.2.11 on 2022-01-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasDetelhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('desconto', models.FloatField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='api.compras')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.produto')),
            ],
            options={
                'verbose_name_plural': 'Detalhes',
            },
        ),
    ]
