# Generated by Django 4.0.1 on 2022-02-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comprasdetelhe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComprasDetelhe',
            new_name='ComprasDetalhe',
        ),
    ]
