# Generated by Django 3.2.11 on 2022-02-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_comprasdetelhe_comprasdetalhe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdetalhe',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe', to='api.compras'),
        ),
    ]
