# Generated by Django 3.2.11 on 2022-02-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220210_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadetalhe',
            name='desconto',
            field=models.FloatField(default=0),
        ),
    ]
