# Generated by Django 3.2.11 on 2022-02-11 00:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220210_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(upload_to='produtos'),
        ),
    ]
