# Generated by Django 4.0.1 on 2022-02-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_vendadetalhe_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadetalhe',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produto', to='api.produto'),
        ),
    ]
