# Generated by Django 3.2.11 on 2022-02-11 00:14

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220210_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
