# Generated by Django 4.0.1 on 2022-02-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_vendadetalhe_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadetalhe',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.produto'),
        ),
    ]
