# Generated by Django 4.0.1 on 2022-03-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.empresa'),
        ),
    ]
