# Generated by Django 3.2.11 on 2022-03-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_venda_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clientes', to='api.cliente'),
        ),
    ]
