# Generated by Django 3.2.11 on 2022-03-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
