# Generated by Django 3.2.11 on 2022-03-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_moeda_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='moeda',
            unique_together={('empresa', 'descricao')},
        ),
    ]
