# Generated by Django 3.2.11 on 2022-03-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220311_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moedas', to='api.empresa'),
        ),
    ]
