# Generated by Django 3.2.11 on 2022-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_lancamentocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
