# Generated by Django 4.0.1 on 2022-03-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_venda_paga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
