# Generated by Django 3.2.11 on 2022-04-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220413_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ManyToManyField(related_name='produtos', through='api.EstoqueEmpresa', to='api.Empresa'),
        ),
    ]
