# Generated by Django 3.2.11 on 2022-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220414_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='produtos', through='api.EstoqueEmpresa', to='api.Empresa'),
        ),
    ]
