# Generated by Django 3.2.11 on 2022-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_produto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='empresa',
            field=models.ManyToManyField(blank=True, default=1, related_name='produtos', through='api.EstoqueEmpresa', to='api.Empresa'),
        ),
    ]
