# Generated by Django 3.2.11 on 2022-04-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_produto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueempresa',
            name='empresa',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoque', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='estoqueempresa',
            name='produto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoque', to='api.produto'),
        ),
    ]
