# Generated by Django 4.0.1 on 2022-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220419_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='estoqueempresa',
            name='deposito7',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
