# Generated by Django 4.0.1 on 2022-06-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_vendadetalhe_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('total', models.FloatField(default=0)),
                ('paga', models.BooleanField(default=False)),
                ('cornecedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cornecedor', to='api.fornecedor')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.empresa')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='CompraDetalhe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0)),
                ('desconto', models.FloatField(default=0)),
                ('deposito', models.IntegerField(default=0)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe', to='api.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.produto')),
            ],
            options={
                'verbose_name_plural': 'Detalhes de Compra',
            },
        ),
        migrations.RemoveField(
            model_name='comprasdetalhe',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='comprasdetalhe',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='ComprasDetalhe',
        ),
    ]
