# Generated by Django 4.0.1 on 2022-06-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_compra_compradetalhe_remove_comprasdetalhe_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cornecedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='fornecedor', to='api.fornecedor'),
            preserve_default=False,
        ),
    ]
