# Generated by Django 4.0.1 on 2022-06-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_categoria_usuario_cliente_usuario_compra_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compradetalhe',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='estoqueempresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lancamentocaixa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='vendadetalhe',
            name='usuario',
        ),
    ]
