# Generated by Django 4.0.1 on 2022-06-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_estoqueempresa_options_contacontabil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacontabil',
            options={'verbose_name_plural': 'Contas Contábeis'},
        ),
        migrations.AlterModelOptions(
            name='lancamentocaixa',
            options={'verbose_name_plural': 'Lancamentos de caixa'},
        ),
        migrations.AddField(
            model_name='lancamentocaixa',
            name='conta_contabil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='lancamentos', to='api.contacontabil'),
            preserve_default=False,
        ),
    ]
