# Generated by Django 4.0.1 on 2022-07-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='classificacaodi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_ultima_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_ultima_venda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao2di',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricaodi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='forncedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='api.fornecedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='iva',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='marcadi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_neto_bruto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_neto_caixa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_atacado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_atacado_dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo_di',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo_dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_ficticio_dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_medio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_origem_dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_por_caixa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
