# Generated by Django 4.0.1 on 2022-07-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_produto_forncedor_produto_fornecedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='peso_neto_bruto',
            new_name='peso_bruto_caixa',
        ),
    ]
