# Generated by Django 3.2.11 on 2022-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_produto_peso_bruto_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='del_foto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
