# Generated by Django 4.0.1 on 2022-07-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_produto_del_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
