# Generated by Django 3.2.11 on 2022-07-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_produto_ncm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAntigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50)),
                ('qtd1', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd2', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd3', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd4', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd5', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd6', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd7', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd8', models.IntegerField(blank=True, default=0, null=True)),
                ('qtd9', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito1', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito2', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito3', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito4', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito5', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito6', models.IntegerField(blank=True, default=0, null=True)),
                ('deposito7', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'ProdutosAntigos',
            },
        ),
    ]
