# Generated by Django 3.2.11 on 2022-07-10 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_produtoantigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueempresa',
            name='produto_antigo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_estoque_antigo', to='api.produtoantigo'),
        ),
    ]
