# Generated by Django 3.2.11 on 2022-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_estoqueempresa_produto_antigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoantigo',
            name='empresa',
            field=models.ManyToManyField(blank=True, default=1, related_name='produtosantigos', through='api.EstoqueEmpresa', to='api.Empresa'),
        ),
    ]
