# Generated by Django 3.2.11 on 2022-07-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_venda_extenso_venda_numero_nf_notafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.empresa'),
        ),
    ]
