# Generated by Django 3.2.11 on 2022-07-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_notafiscal_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacional',
            field=models.BooleanField(default=False),
        ),
    ]
