# Generated by Django 4.0.1 on 2022-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_cliente_endereco_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento_nf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
