# Generated by Django 4.0.1 on 2022-07-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('listar_clientes', 'Usuário pode listar clientes'),), 'verbose_name_plural': 'Clientes'},
        ),
    ]
