# Generated by Django 3.2.11 on 2022-07-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('listar_categorias', 'Usuário pode listar categorias'),), 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': (('listar_compras', 'Usuário pode listar compras'),), 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='contacontabil',
            options={'permissions': (('listar_contacontabil', 'Usuário pode listar conta contabil'),), 'verbose_name_plural': 'Contas Contábeis'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': (('listar_empresas', 'Usuário pode listar empresas'),), 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'permissions': (('listar_fornecedores', 'Usuário pode listar fornecedores'),), 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='lancamentocaixa',
            options={'permissions': (('listar_lancamentoscaixa', 'Usuário pode listar lançamentos do caixa'),), 'verbose_name_plural': 'Lancamentos de caixa'},
        ),
        migrations.AlterModelOptions(
            name='moeda',
            options={'permissions': (('listar_moedas', 'Usuário pode listar moedas'),), 'verbose_name_plural': 'moedas'},
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'permissions': (('listar_notafiscal', 'Usuário pode listar notafiscal'), ('emitir_notafiscal', 'Usuário pode emitir notafiscal'))},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'permissions': (('listar_produtos', 'Usuário pode listar produtos'),), 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'permissions': (('listar_subcategorias', 'Usuário pode listar subcategorias'),), 'verbose_name_plural': 'Sub Categorias'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('listar_vendas', 'Usuário pode listar vendas'),), 'verbose_name_plural': 'Vendas'},
        ),
    ]
