GET http://localhost:8000/rest/v1/docs/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQyODk0NTA5LCJpYXQiOjE2NDI4OTQyMDksImp0aSI6ImQ4ZjU2YWY1MzZhYjQ5OWVhNzk1YTBhNGYzYzk5NjAwIiwidXNlcl9pZCI6MX0.sUrcChYm64fG5oHZhLBAJ445KtYpHhOXx5DSSBlmAxw



POST http://localhost:8000/rest/v1/docs/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQzMjg2NTI2LCJpYXQiOjE2NDMyODYyMjYsImp0aSI6ImM4YjM1MDY1MTJhZDQ0MmJiYmQzOTNhNDc2MWM4N2JlIiwidXNlcl9pZCI6MX0.GKIXQIAVLaN0CyEHPkCKTieVMiMlZwT4nIGis13HSNw

{
    "nombre": "F2 dezembro",
    "expira": "2025-08-06",
    "alerta1y": false,
    "alerta6m": false,
    "alerta3m": false,
    "alerta1m": true
}


PUT http://localhost:8000/rest/v1/docs/1/
Content-Type: application/json

{
    "nombre": "F2 dezembro",
    "expira": "2040-08-05",
    "alerta1y": false,
    "alerta6m": false,
    "alerta3m": false,
    "alerta1m": true
}


POST http://192.168.1.191:8000/rest/v1/token/
Content-Type: application/json

{
    "username": "conejofoz",
    "password": "1234567."
}



POST http://localhost:8000/rest/v1/categoria/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQzMjg2NTI2LCJpYXQiOjE2NDMyODYyMjYsImp0aSI6ImM4YjM1MDY1MTJhZDQ0MmJiYmQzOTNhNDc2MWM4N2JlIiwidXNlcl9pZCI6MX0.GKIXQIAVLaN0CyEHPkCKTieVMiMlZwT4nIGis13HSNw

{
    "descricao": "Perfumes"
}



http://localhost:8000/rest/v1/subcategoria/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjQzNDc4Mjc1LCJpYXQiOjE2NDM0Nzc5NzUsImp0aSI6ImU4MjMxODg1OWIxNzQ2ZDdiMDYzZDYxNjlmYmE4NjdiIiwidXNlcl9pZCI6MX0.bWr4J0xbQ19KZszZJZg5Uy0YffWPYIosk9M_PBqnk1M
